name: Call API every minute

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Execute curl command
        run: |
          curl https://new-relic-logger.vercel.app/api/cron
